
import type { Metadata } from "next";
import Navbar from "@/components/Comment/Navbar";
import Footer from "@/components/Comment/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <>
      <Navbar />
      <main className="bg-white">

        {children}
      </main>
      <Footer />
    </>
  );
}
